# environment.yml (Revised)
name: scrnaseq_agent_env  # Let's stick to the original name
channels:
  - conda-forge          # PRIORITIZE conda-forge
  - bioconda
  - defaults
  - pytorch             # Add pytorch channel for its packages if needed
dependencies:
  - python=3.10         # Pin to 3.10
  - pip
  - scanpy>=1.9
  - python-igraph       # Explicitly add dependencies often needed
  - leidenalg
  - anndata>=0.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib-base
  - seaborn
  - pyyaml
  - click
  - pytest
  - numba               # Explicitly add numba (scanpy/umap needs it)
  - llvmlite            # Numba dependency
  - scikit-misc
  -pytest-mock
  # Try *without* explicitly adding pytorch first.
  # Let scanpy pull it via conda-forge if needed.
  # If errors persist, uncommenting might help (choose one):
  # - pytorch::pytorch  # Get pytorch from its own channel
  # - pytorch::cpuonly # Force CPU-only version
  # - boto3             # For AWS S3 later
  # - pip:
  #   - pre-commit